name: EventManager
main: com.pushkraj.eventmanager.EventManager
version: 1.0
api-version: '1.21'
author: Pushkraj
description: A PaperMC plugin for Minecraft.
commands:
  eventmanager:
    description: Opens the EventManager GUI.
    usage: /<command>
    aliases: [em]
    permission: eventmanager.gui
permissions:
  eventmanager.gui:
    description: Allows opening the EventManager GUI.
    default: op
  eventmanager.toggle.chatmute:
    description: Allows toggling the global chat mute.
    default: op
  eventmanager.broadcast:
    description: Allows broadcasting messages via the EventManager GUI.
    default: op
  eventmanager.chat.bypass:
    description: Allows a player to chat even when global chat is muted.
    default: op
  eventmanager.toggle.adminautovanish:
    description: Allows toggling the admin auto vanish feature.
    default: op
  eventmanager.admin.autovanish:
    description: Allows an admin to automatically vanish on join if the feature is enabled.
    default: op
  eventmanager.toggle.autorestart:
    description: Allows toggling the auto restart timer.
    default: op